create_ip -name axi_interconnect -vendor xilinx.com -library ip -version 1.7 -module_name axi_itct
set_property -dict [list \
  CONFIG.NUM_SLAVE_PORTS {1} \
  CONFIG.INTERCONNECT_DATA_WIDTH {512} \
  CONFIG.S00_AXI_DATA_WIDTH {512} \
  CONFIG.M00_AXI_DATA_WIDTH {256} \
  CONFIG.S00_AXI_WRITE_FIFO_DEPTH {512} \
  CONFIG.S00_AXI_WRITE_FIFO_DELAY {1} \
  CONFIG.S00_AXI_READ_FIFO_DEPTH {512} \
  CONFIG.S00_AXI_READ_FIFO_DELAY {1} \
  CONFIG.M00_AXI_IS_ACLK_ASYNC {1} \
  CONFIG.M00_AXI_WRITE_FIFO_DEPTH {512} \
  CONFIG.M00_AXI_READ_FIFO_DEPTH {512} \
  CONFIG.M00_AXI_WRITE_FIFO_DELAY {1} \
  CONFIG.M00_AXI_READ_FIFO_DELAY {1} \
  CONFIG.S00_AXI_REGISTER {1} \
  CONFIG.M00_AXI_REGISTER {1} \
] [get_ips axi_itct]