create_clock -period 10.000       [get_ports init_clk]
set_property PACKAGE_PIN G18      [get_ports init_clk]
set_property IOSTANDARD LVCMOS18  [get_ports init_clk]

set_property PACKAGE_PIN AN40 [get_ports gt0_ref_clk_p]
set_property PACKAGE_PIN AN41 [get_ports gt0_ref_clk_n]

set_property PACKAGE_PIN AU49 [get_ports {gt0_txn_out[0]}]
set_property PACKAGE_PIN AU48 [get_ports {gt0_txp_out[0]}]
set_property PACKAGE_PIN AU54 [get_ports {gt0_rxn_in[0]}]
set_property PACKAGE_PIN AU53 [get_ports {gt0_rxp_in[0]}]
set_property PACKAGE_PIN AT47 [get_ports {gt0_txn_out[1]}]
set_property PACKAGE_PIN AT46 [get_ports {gt0_txp_out[1]}]
set_property PACKAGE_PIN AT52 [get_ports {gt0_rxn_in[1]}]
set_property PACKAGE_PIN AT51 [get_ports {gt0_rxp_in[1]}]
set_property PACKAGE_PIN AR49 [get_ports {gt0_txn_out[2]}]
set_property PACKAGE_PIN AR48 [get_ports {gt0_txp_out[2]}]
set_property PACKAGE_PIN AR54 [get_ports {gt0_rxn_in[2]}]
set_property PACKAGE_PIN AR53 [get_ports {gt0_rxp_in[2]}]
set_property PACKAGE_PIN AR45 [get_ports {gt0_txn_out[3]}]
set_property PACKAGE_PIN AR44 [get_ports {gt0_txp_out[3]}]
set_property PACKAGE_PIN AP52 [get_ports {gt0_rxn_in[3]}]
set_property PACKAGE_PIN AP51 [get_ports {gt0_rxp_in[3]}]

set_property PACKAGE_PIN BG23       [get_ports qsfp0_modesel_l]
set_property IOSTANDARD  LVCMOS18   [get_ports qsfp0_modesel_l]
set_property PACKAGE_PIN BF21       [get_ports qsfp0_reset_l]
set_property IOSTANDARD  LVCMOS18   [get_ports qsfp0_reset_l]
set_property PACKAGE_PIN BG22       [get_ports qsfp0_lpmode]
set_property IOSTANDARD  LVCMOS18   [get_ports qsfp0_lpmode]
set_property PACKAGE_PIN D16        [get_ports qsfp0_fs]
set_property IOSTANDARD  LVCMOS18   [get_ports qsfp0_fs]
set_property PACKAGE_PIN D17        [get_ports qsfp0_oeb]
set_property IOSTANDARD  LVCMOS18   [get_ports qsfp0_oeb]